name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - "config/**"

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
  
      - name: Install pipx
        run: python3 -m pip install --user pipx
  
      - name: Ensure pipx binary is on PATH
        run: ~/.local/bin/pipx ensurepath
  
      - name: Install keymap-drawer with pipx
        run: pipx install "git+https://github.com/caksoylar/keymap-drawer.git@main"

  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    needs: install

  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    needs: install
    permissions:
      contents: write
    with:
      commit_message: "[Draw] ${{ github.event.head_commit.message }}"
      amend_commit: false
      install_branch: "main"
      keymap_patterns: "config/*.keymap"
      json_path: "config"
      config_path: "keymap_drawer.config.yaml"
      output_folder: "keymap-drawer"
      destination: "both"
      parse_args: ""
      draw_args: ""
